### ISSUE TITLE
Change callbacks for promises

### ISSUE THREAD

**Issue by miguelrgonzalez** [miguelrgonzalez/mlsound#8]

**Comment by dmcassel** [comment]
Completely rewriting will take time and there will be some complexity. I suggest being okay with partial progress, or using Promises for new features. 

What Promises library should be used? (The MarkLogic Node.js Client API uses [Bluebird](https://github.com/petkaantonov/bluebird).)

**Comment by miguelrgonzalez** [comment]
Never used bluebird myself, but I'm OK with using that library.
